// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: protobufs/measurements.proto

package com.timmattison.pitfalls.domain;

public final class MeasurementsProtos {
  private MeasurementsProtos() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public interface MedicalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:domain.Medical)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 weightInGrams = 1;</code>
     */
    boolean hasWeightInGrams();
    /**
     * <code>required int64 weightInGrams = 1;</code>
     */
    long getWeightInGrams();

    /**
     * <code>required int64 heightInMillimeters = 2;</code>
     */
    boolean hasHeightInMillimeters();
    /**
     * <code>required int64 heightInMillimeters = 2;</code>
     */
    long getHeightInMillimeters();
  }
  /**
   * Protobuf type {@code domain.Medical}
   */
  public static final class Medical extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:domain.Medical)
      MedicalOrBuilder {
    // Use Medical.newBuilder() to construct.
    private Medical(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Medical(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Medical defaultInstance;
    public static Medical getDefaultInstance() {
      return defaultInstance;
    }

    public Medical getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Medical(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              weightInGrams_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              heightInMillimeters_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Medical_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Medical_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.class, com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.Builder.class);
    }

    public static com.google.protobuf.Parser<Medical> PARSER =
        new com.google.protobuf.AbstractParser<Medical>() {
      public Medical parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Medical(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Medical> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int WEIGHTINGRAMS_FIELD_NUMBER = 1;
    private long weightInGrams_;
    /**
     * <code>required int64 weightInGrams = 1;</code>
     */
    public boolean hasWeightInGrams() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 weightInGrams = 1;</code>
     */
    public long getWeightInGrams() {
      return weightInGrams_;
    }

    public static final int HEIGHTINMILLIMETERS_FIELD_NUMBER = 2;
    private long heightInMillimeters_;
    /**
     * <code>required int64 heightInMillimeters = 2;</code>
     */
    public boolean hasHeightInMillimeters() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 heightInMillimeters = 2;</code>
     */
    public long getHeightInMillimeters() {
      return heightInMillimeters_;
    }

    private void initFields() {
      weightInGrams_ = 0L;
      heightInMillimeters_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasWeightInGrams()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasHeightInMillimeters()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, weightInGrams_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, heightInMillimeters_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, weightInGrams_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, heightInMillimeters_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.timmattison.pitfalls.domain.MeasurementsProtos.Medical prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code domain.Medical}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:domain.Medical)
        com.timmattison.pitfalls.domain.MeasurementsProtos.MedicalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Medical_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Medical_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.class, com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.Builder.class);
      }

      // Construct using com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        weightInGrams_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        heightInMillimeters_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Medical_descriptor;
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Medical getDefaultInstanceForType() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.getDefaultInstance();
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Medical build() {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Medical result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Medical buildPartial() {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Medical result = new com.timmattison.pitfalls.domain.MeasurementsProtos.Medical(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.weightInGrams_ = weightInGrams_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.heightInMillimeters_ = heightInMillimeters_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.timmattison.pitfalls.domain.MeasurementsProtos.Medical) {
          return mergeFrom((com.timmattison.pitfalls.domain.MeasurementsProtos.Medical)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.timmattison.pitfalls.domain.MeasurementsProtos.Medical other) {
        if (other == com.timmattison.pitfalls.domain.MeasurementsProtos.Medical.getDefaultInstance()) return this;
        if (other.hasWeightInGrams()) {
          setWeightInGrams(other.getWeightInGrams());
        }
        if (other.hasHeightInMillimeters()) {
          setHeightInMillimeters(other.getHeightInMillimeters());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasWeightInGrams()) {
          
          return false;
        }
        if (!hasHeightInMillimeters()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Medical parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.timmattison.pitfalls.domain.MeasurementsProtos.Medical) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long weightInGrams_ ;
      /**
       * <code>required int64 weightInGrams = 1;</code>
       */
      public boolean hasWeightInGrams() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 weightInGrams = 1;</code>
       */
      public long getWeightInGrams() {
        return weightInGrams_;
      }
      /**
       * <code>required int64 weightInGrams = 1;</code>
       */
      public Builder setWeightInGrams(long value) {
        bitField0_ |= 0x00000001;
        weightInGrams_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 weightInGrams = 1;</code>
       */
      public Builder clearWeightInGrams() {
        bitField0_ = (bitField0_ & ~0x00000001);
        weightInGrams_ = 0L;
        onChanged();
        return this;
      }

      private long heightInMillimeters_ ;
      /**
       * <code>required int64 heightInMillimeters = 2;</code>
       */
      public boolean hasHeightInMillimeters() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 heightInMillimeters = 2;</code>
       */
      public long getHeightInMillimeters() {
        return heightInMillimeters_;
      }
      /**
       * <code>required int64 heightInMillimeters = 2;</code>
       */
      public Builder setHeightInMillimeters(long value) {
        bitField0_ |= 0x00000002;
        heightInMillimeters_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 heightInMillimeters = 2;</code>
       */
      public Builder clearHeightInMillimeters() {
        bitField0_ = (bitField0_ & ~0x00000002);
        heightInMillimeters_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:domain.Medical)
    }

    static {
      defaultInstance = new Medical(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:domain.Medical)
  }

  public interface AstronomicalOrBuilder extends
      // @@protoc_insertion_point(interface_extends:domain.Astronomical)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>required int64 id = 1;</code>
     */
    boolean hasId();
    /**
     * <code>required int64 id = 1;</code>
     */
    long getId();

    /**
     * <code>required int64 sizeInAttoParsecs = 2;</code>
     */
    boolean hasSizeInAttoParsecs();
    /**
     * <code>required int64 sizeInAttoParsecs = 2;</code>
     */
    long getSizeInAttoParsecs();
  }
  /**
   * Protobuf type {@code domain.Astronomical}
   */
  public static final class Astronomical extends
      com.google.protobuf.GeneratedMessage implements
      // @@protoc_insertion_point(message_implements:domain.Astronomical)
      AstronomicalOrBuilder {
    // Use Astronomical.newBuilder() to construct.
    private Astronomical(com.google.protobuf.GeneratedMessage.Builder<?> builder) {
      super(builder);
      this.unknownFields = builder.getUnknownFields();
    }
    private Astronomical(boolean noInit) { this.unknownFields = com.google.protobuf.UnknownFieldSet.getDefaultInstance(); }

    private static final Astronomical defaultInstance;
    public static Astronomical getDefaultInstance() {
      return defaultInstance;
    }

    public Astronomical getDefaultInstanceForType() {
      return defaultInstance;
    }

    private final com.google.protobuf.UnknownFieldSet unknownFields;
    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
        getUnknownFields() {
      return this.unknownFields;
    }
    private Astronomical(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      initFields();
      int mutable_bitField0_ = 0;
      com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder();
      try {
        boolean done = false;
        while (!done) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              done = true;
              break;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                done = true;
              }
              break;
            }
            case 8: {
              bitField0_ |= 0x00000001;
              id_ = input.readInt64();
              break;
            }
            case 16: {
              bitField0_ |= 0x00000002;
              sizeInAttoParsecs_ = input.readInt64();
              break;
            }
          }
        }
      } catch (com.google.protobuf.InvalidProtocolBufferException e) {
        throw e.setUnfinishedMessage(this);
      } catch (java.io.IOException e) {
        throw new com.google.protobuf.InvalidProtocolBufferException(
            e.getMessage()).setUnfinishedMessage(this);
      } finally {
        this.unknownFields = unknownFields.build();
        makeExtensionsImmutable();
      }
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Astronomical_descriptor;
    }

    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Astronomical_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.class, com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.Builder.class);
    }

    public static com.google.protobuf.Parser<Astronomical> PARSER =
        new com.google.protobuf.AbstractParser<Astronomical>() {
      public Astronomical parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        return new Astronomical(input, extensionRegistry);
      }
    };

    @java.lang.Override
    public com.google.protobuf.Parser<Astronomical> getParserForType() {
      return PARSER;
    }

    private int bitField0_;
    public static final int ID_FIELD_NUMBER = 1;
    private long id_;
    /**
     * <code>required int64 id = 1;</code>
     */
    public boolean hasId() {
      return ((bitField0_ & 0x00000001) == 0x00000001);
    }
    /**
     * <code>required int64 id = 1;</code>
     */
    public long getId() {
      return id_;
    }

    public static final int SIZEINATTOPARSECS_FIELD_NUMBER = 2;
    private long sizeInAttoParsecs_;
    /**
     * <code>required int64 sizeInAttoParsecs = 2;</code>
     */
    public boolean hasSizeInAttoParsecs() {
      return ((bitField0_ & 0x00000002) == 0x00000002);
    }
    /**
     * <code>required int64 sizeInAttoParsecs = 2;</code>
     */
    public long getSizeInAttoParsecs() {
      return sizeInAttoParsecs_;
    }

    private void initFields() {
      id_ = 0L;
      sizeInAttoParsecs_ = 0L;
    }
    private byte memoizedIsInitialized = -1;
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      if (!hasId()) {
        memoizedIsInitialized = 0;
        return false;
      }
      if (!hasSizeInAttoParsecs()) {
        memoizedIsInitialized = 0;
        return false;
      }
      memoizedIsInitialized = 1;
      return true;
    }

    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        output.writeInt64(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        output.writeInt64(2, sizeInAttoParsecs_);
      }
      getUnknownFields().writeTo(output);
    }

    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;

      size = 0;
      if (((bitField0_ & 0x00000001) == 0x00000001)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(1, id_);
      }
      if (((bitField0_ & 0x00000002) == 0x00000002)) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt64Size(2, sizeInAttoParsecs_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }

    private static final long serialVersionUID = 0L;
    @java.lang.Override
    protected java.lang.Object writeReplace()
        throws java.io.ObjectStreamException {
      return super.writeReplace();
    }

    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseDelimitedFrom(input, extensionRegistry);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return PARSER.parseFrom(input);
    }
    public static com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return PARSER.parseFrom(input, extensionRegistry);
    }

    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessage.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * Protobuf type {@code domain.Astronomical}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:domain.Astronomical)
        com.timmattison.pitfalls.domain.MeasurementsProtos.AstronomicalOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Astronomical_descriptor;
      }

      protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Astronomical_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.class, com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.Builder.class);
      }

      // Construct using com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.newBuilder()
      private Builder() {
        maybeForceBuilderInitialization();
      }

      private Builder(
          com.google.protobuf.GeneratedMessage.BuilderParent parent) {
        super(parent);
        maybeForceBuilderInitialization();
      }
      private void maybeForceBuilderInitialization() {
        if (com.google.protobuf.GeneratedMessage.alwaysUseFieldBuilders) {
        }
      }
      private static Builder create() {
        return new Builder();
      }

      public Builder clear() {
        super.clear();
        id_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000001);
        sizeInAttoParsecs_ = 0L;
        bitField0_ = (bitField0_ & ~0x00000002);
        return this;
      }

      public Builder clone() {
        return create().mergeFrom(buildPartial());
      }

      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.internal_static_domain_Astronomical_descriptor;
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical getDefaultInstanceForType() {
        return com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.getDefaultInstance();
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical build() {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      public com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical buildPartial() {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical result = new com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical(this);
        int from_bitField0_ = bitField0_;
        int to_bitField0_ = 0;
        if (((from_bitField0_ & 0x00000001) == 0x00000001)) {
          to_bitField0_ |= 0x00000001;
        }
        result.id_ = id_;
        if (((from_bitField0_ & 0x00000002) == 0x00000002)) {
          to_bitField0_ |= 0x00000002;
        }
        result.sizeInAttoParsecs_ = sizeInAttoParsecs_;
        result.bitField0_ = to_bitField0_;
        onBuilt();
        return result;
      }

      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical) {
          return mergeFrom((com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical other) {
        if (other == com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical.getDefaultInstance()) return this;
        if (other.hasId()) {
          setId(other.getId());
        }
        if (other.hasSizeInAttoParsecs()) {
          setSizeInAttoParsecs(other.getSizeInAttoParsecs());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }

      public final boolean isInitialized() {
        if (!hasId()) {
          
          return false;
        }
        if (!hasSizeInAttoParsecs()) {
          
          return false;
        }
        return true;
      }

      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical parsedMessage = null;
        try {
          parsedMessage = PARSER.parsePartialFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          parsedMessage = (com.timmattison.pitfalls.domain.MeasurementsProtos.Astronomical) e.getUnfinishedMessage();
          throw e;
        } finally {
          if (parsedMessage != null) {
            mergeFrom(parsedMessage);
          }
        }
        return this;
      }
      private int bitField0_;

      private long id_ ;
      /**
       * <code>required int64 id = 1;</code>
       */
      public boolean hasId() {
        return ((bitField0_ & 0x00000001) == 0x00000001);
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public long getId() {
        return id_;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder setId(long value) {
        bitField0_ |= 0x00000001;
        id_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 id = 1;</code>
       */
      public Builder clearId() {
        bitField0_ = (bitField0_ & ~0x00000001);
        id_ = 0L;
        onChanged();
        return this;
      }

      private long sizeInAttoParsecs_ ;
      /**
       * <code>required int64 sizeInAttoParsecs = 2;</code>
       */
      public boolean hasSizeInAttoParsecs() {
        return ((bitField0_ & 0x00000002) == 0x00000002);
      }
      /**
       * <code>required int64 sizeInAttoParsecs = 2;</code>
       */
      public long getSizeInAttoParsecs() {
        return sizeInAttoParsecs_;
      }
      /**
       * <code>required int64 sizeInAttoParsecs = 2;</code>
       */
      public Builder setSizeInAttoParsecs(long value) {
        bitField0_ |= 0x00000002;
        sizeInAttoParsecs_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>required int64 sizeInAttoParsecs = 2;</code>
       */
      public Builder clearSizeInAttoParsecs() {
        bitField0_ = (bitField0_ & ~0x00000002);
        sizeInAttoParsecs_ = 0L;
        onChanged();
        return this;
      }

      // @@protoc_insertion_point(builder_scope:domain.Astronomical)
    }

    static {
      defaultInstance = new Astronomical(true);
      defaultInstance.initFields();
    }

    // @@protoc_insertion_point(class_scope:domain.Astronomical)
  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_Medical_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_domain_Medical_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_domain_Astronomical_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_domain_Astronomical_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\034protobufs/measurements.proto\022\006domain\"=" +
      "\n\007Medical\022\025\n\rweightInGrams\030\001 \002(\003\022\033\n\023heig" +
      "htInMillimeters\030\002 \002(\003\"5\n\014Astronomical\022\n\n" +
      "\002id\030\001 \002(\003\022\031\n\021sizeInAttoParsecs\030\002 \002(\003B5\n\037" +
      "com.timmattison.pitfalls.domainB\022Measure" +
      "mentsProtos"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
        new com.google.protobuf.Descriptors.FileDescriptor.    InternalDescriptorAssigner() {
          public com.google.protobuf.ExtensionRegistry assignDescriptors(
              com.google.protobuf.Descriptors.FileDescriptor root) {
            descriptor = root;
            return null;
          }
        };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
        }, assigner);
    internal_static_domain_Medical_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_domain_Medical_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_domain_Medical_descriptor,
        new java.lang.String[] { "WeightInGrams", "HeightInMillimeters", });
    internal_static_domain_Astronomical_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_domain_Astronomical_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessage.FieldAccessorTable(
        internal_static_domain_Astronomical_descriptor,
        new java.lang.String[] { "Id", "SizeInAttoParsecs", });
  }

  // @@protoc_insertion_point(outer_class_scope)
}
